---
- name: Secure | Setup alternate SSH port and password
  vars:
    sshd:
      - name: SSH port
        regexp: "^#Port 22"
        line: "Port 1797"
      - name: SSH password
        regexp: "^#PasswordAuthentication yes"
        line: "PasswordAuthentication no"
  ansible.builtin.lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ sshd }}"
  notify: restart sshd
  tags:
    - configuration
    - secure
    - secure-ssh

- name: Secure | Set authorized key taken from file
  ansible.posix.authorized_key:
    user: hlc
    state: present
    key: "{{ lookup('file', '/home/hlc/.ssh/id_rsa.pub') }}"
  notify: restart sshd
  tags:
    - configuration
    - secure
    - secure-authorized

- name: Secure | UFW state disable
  ansible.builtin.ufw:
    state: "{{ ufw_state_disable }}"
  when: ufw_state_disable is defined
  tags:
    - configuration
    - secure
    - secure-disable-service-ufw

- name: Secure | Defaults of SMTP
  vars:
    defaults:
      - direction: "incoming"
        policy: "deny"
      - direction: "outgoing"
        policy: "allow"
  ansible.builtin.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items: "{{ defaults }}"
  tags:
    - configuration
    - secure
    - secure-ufw-configure

- name: Secure | Allow list ip to port {{ postfix_bind_port }} of SMTP
  vars:
    smtp:
      - src: 192.168.48.0/24
        comment: "Allow SMTP from Email-ODS with Network LAN"
      - src: 103.15.48.0/24
        comment: "Allow SMTP from Email-ODS with Network WAN"
  ansible.builtin.ufw:
    rule: allow
    src: "{{ item.src }}"
    port: "{{ postfix_bind_port }}"
    proto: tcp
    comment: "{{ item.comment }}"
  loop: "{{ smtp }}"
  tags:
    - configuration
    - secure
    - secure-ufw-configure

- name: Secure | Allow list ip to port 161 of SMTP in Cluster SMTP
  vars:
    snmpd:
      - src: 192.168.102.179
        comment: "Allow SNMPD from Zabbix-ODS with Network LAN"
      - src: 103.138.88.254
        comment: "Allow SNMPD from Zabbix-VDC with Network WAN"
  ansible.builtin.ufw:
    rule: allow
    src: "{{ item.src }}"
    port: 161
    proto: tcp
    comment: "{{ item.comment }}"
  with_items: "{{ snmpd }}"
  tags:
    - configuration
    - secure
    - secure-ufw-configure

- name: Secure | Allow list ip to port 1797 of SMTP in Cluster SMTP
  vars:
    sshd:
      - src: 103.15.48.41
        comment: "Allow SSH from Guacamole-ODS with Network WAN"
      - src: 192.168.48.41
        comment: "Allow SSH from Guacamole-ODS with Network LAN"
      - src: 103.15.48.218
        comment: "Allow SSH from Tools-ODS with Network WAN"
      - src: 192.168.48.218
        comment: "Allow SSH from Tools-ODS with Network LAN"
      - src: 103.138.88.254
        comment: "Allow SSH from Tools-VDC with Network WAN"
      - src: 192.168.88.254
        comment: "Allow SSH from Tools-VDC with Network LAN"
  ansible.builtin.ufw:
    rule: allow
    src: "{{ item.src }}"
    port: 1797
    proto: tcp
    comment: "{{ item.comment }}"
  with_items: "{{ sshd }}"
  tags:
    - configuration
    - secure
    - secure-ufw-configure

- name: Secure | SSH restarted
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  tags:
    - configuration
    - secure
    - secure-restart-service-ssh

- name: Secure | UFW state enabled
  ansible.builtin.ufw:
    state: "{{ ufw_state_enable }}"
  when: ufw_state_enable is defined
  tags:
    - configuration
    - secure
    - secure-enable-service-ufw
