---
- name: Prepare | Wait for /var/lib/dpkg/lock-frontend to be released
  ansible.builtin.shell: >
    while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;
  changed_when: false
  tags:
    - configuration
    - snmpd
    - snmpd-lock-frontend

- name: Prepare | Installing packages dependencies of snmpd
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ snmpd_package }}"
  tags:
    - configuration
    - snmpd
    - snmpd-package

- name: SNMPD | Temporary stop snmpd service
  ansible.builtin.systemd:
    name: snmpd
    state: stopped
  tags:
    - configuration
    - snmpd
    - snmpd-stop-service

- name: SNMPD | Update configuration file(s) - [snmpd.conf]
  ansible.builtin.copy:
    src: "etc/snmp/snmpd.conf"
    dest: "/etc/snmp/snmpd.conf"
    owner: root
    group: root
    mode: 0600
  tags:
    - configuration
    - snmpd
    - snmpd-config

- name: SNMPD | Update configuration auth file(s) - [snmpd.conf]
  vars:
    snmp_user: 'zabbixsnmp'
    snmp_privpass: 'd4N*XBcGp@AVNYvQyP'
    snmp_authpass: 'Yyk.Jo76UZAgq@Et4G'
  ansible.builtin.shell: >
    net-snmp-create-v3-user -ro -A "{{ snmp_authpass }}" -a SHA -X "{{ snmp_privpass }}" -x AES "{{ snmp_user }}"
  changed_when: false
  tags:
    - configuration
    - snmpd
    - snmpd-create-user

- name: SNMPD | Update file [CPU-Master, RAM-Master, DISK-Master and Services-Master]
  ansible.builtin.copy:
    src: "etc/snmp/scripts"
    dest: "/etc/snmp/"
    owner: root
    group: root
    mode: 0755
  notify: restart snmpd
  tags:
    - configuration
    - snmpd
    - snmpd-scripts
