#!/bin/bash
DISK=`df / | awk 'NR==2 {printf("%d %d %d %d",$2,$3,$4,$5)}'`

# Retrieve each element for DISK
DISK_Total=`echo $DISK | awk '{print $1}'`
DISK_Used=`echo $DISK | awk '{print $2}'`
DISK_Avail=`echo $DISK | awk '{print $3}'`

# Create JSON string for DISK
echo "$DISK_Total - $DISK_Used - $DISK_Avail"| \
awk \
'{printf("{\
\"DISK_TOTAL\":%d ,\
\"DISK_USED\":%d ,\
\"DISK_AVAIL\":%d}" ,\
$1,$3,$5)}'
